// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7U_dX8lfkcesKHWTHelGG43vd9oAxjE',
    appId: '1:837090081320:android:c3db467b298a154689d31d',
    messagingSenderId: '837090081320',
    projectId: 'cowealth-bwu',
    databaseURL: 'https://cowealth-bwu-default-rtdb.firebaseio.com',
    storageBucket: 'cowealth-bwu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5cP246nWfGXM164kXPocdd2NOAjpW_mM',
    appId: '1:837090081320:ios:dc003faf3408fad589d31d',
    messagingSenderId: '837090081320',
    projectId: 'cowealth-bwu',
    databaseURL: 'https://cowealth-bwu-default-rtdb.firebaseio.com',
    storageBucket: 'cowealth-bwu.appspot.com',
    androidClientId: '837090081320-5kti6jktbem7trj8eknd7dqj8upqrr1p.apps.googleusercontent.com',
    iosClientId: '837090081320-rnkpdbe9hae5o5gis75hlbdq47qfmrt9.apps.googleusercontent.com',
    iosBundleId: 'com.compiler.cowealth',
  );
}
